import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {KEY} from './core.js';

test('Start speaks once; pause/resume, reload, storage synchronization and ticks never replay it',async()=>{
  const elements=new Map();
  for(const [,id] of readFileSync(new URL('./index.html',import.meta.url),'utf8').matchAll(/id="([^"]+)"/g)) {
    elements.set(id,{style:{},value:'6',checked:false,disabled:false,hidden:false,textContent:'',innerHTML:'',listeners:{},addEventListener(name,callback){this.listeners[name]=callback;},showModal(){this.open=true;},close(){this.open=false;}});
  }
  const windowEvents={};const documentEvents={};const speech=[];const data=new Map();
  globalThis.document={title:'',visibilityState:'visible',getElementById:id=>elements.get(id),addEventListener:(e,fn)=>documentEvents[e]=fn};
  globalThis.window={addEventListener:(e,fn)=>windowEvents[e]=fn,speechSynthesis:{getVoices:()=>[],cancel(){},speak:u=>speech.push(u)},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};
  let toneCount=0;
  const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}});
  window.AudioContext=class{constructor(){this.currentTime=0;this.state='running';this.destination={};}async resume(){}createGain(){return {gain:param(),connect(){},disconnect(){}};}createOscillator(){toneCount++;return {frequency:param(),detune:param(),connect(){},disconnect(){},start(){},stop(){}};}};
  globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};
  const realInterval=globalThis.setInterval;let tick;
  globalThis.setInterval=fn=>{tick=fn;return 0;};
  const realNow=Date.now;let now=Date.parse('2026-09-10T10:00:00Z');Date.now=()=>now;
  try {
    await import('./app.js?first');
    assert.equal(speech.length,0);assert.equal(data.size,0);assert.equal(elements.get('countdown').textContent,'06:00');
    elements.get('start').listeners.click();assert.equal(speech.length,1);
    now+=10000;tick();assert.equal(elements.get('countdown').textContent,'05:50');
    elements.get('start').listeners.click();now+=30000;tick();assert.equal(elements.get('countdown').textContent,'05:50');
    elements.get('start').listeners.click();assert.equal(speech.length,1);
    await import('./app.js?reload');assert.equal(speech.length,1);
    windowEvents.storage({key:KEY,newValue:data.get(KEY)});documentEvents.visibilitychange();assert.equal(speech.length,1);
    now+=500000;tick();assert.equal(elements.get('countdown').textContent,'00:00');assert.equal(elements.get('start-label').textContent,'Meditate again');
    elements.get('start').listeners.click();assert.equal(speech.length,2);
    elements.get('reset').listeners.click();assert.equal(elements.get('countdown').textContent,'06:00');
    assert.ok(JSON.parse(data.get(KEY)).startDate);
    elements.get('voice').checked=false;elements.get('voice').listeners.change();
    elements.get('bell').checked=true;elements.get('bell').listeners.change();
    elements.get('music').checked=true;elements.get('music').listeners.change();
    elements.get('music-volume').value='14';elements.get('music-volume').listeners.input();
    elements.get('start').listeners.click();
    for(let i=0;i<8;i++)await Promise.resolve();
    assert.equal(speech.length,2,'disabled opening voice must remain silent');assert.equal(toneCount,12,'music begins on Start');
    elements.get('voice').checked=true;elements.get('voice').listeners.change();assert.equal(speech.length,2,'enabling voice mid-session must not speak');
    now+=400000;tick();for(let i=0;i<8;i++)await Promise.resolve();assert.equal(toneCount,18,'one gong contains exactly six partials');
    tick();tick();assert.equal(toneCount,18,'completion gong cannot repeat on timer ticks');
    elements.get('silence').listeners.click();
    const muted=JSON.parse(data.get(KEY));assert.equal(muted.voice,false);assert.equal(muted.bell,false);assert.equal(muted.music,false);assert.equal(muted.musicVolume,14);
    elements.get('start').listeners.click();for(let i=0;i<8;i++)await Promise.resolve();assert.equal(speech.length,2);assert.equal(toneCount,18,'silent sessions create no sound');
    elements.get('reset').listeners.click();
    const originalDate=JSON.parse(data.get(KEY)).startDate;
    for(const id of ['breath','listening','gaze','joy']){
      elements.get('technique').value=id;elements.get('technique').listeners.change();
      assert.equal(JSON.parse(data.get(KEY)).technique,id);
      assert.notEqual(elements.get('mantra-title').textContent,'Baba Nam Kevalam');
      assert.equal(elements.get('technique-source').hidden,false);
      assert.equal(elements.get('practice-reading').hidden,false);assert.match(elements.get('practice-reading').href,/^https:\/\/oshoworld\.com\//);
    }
    elements.get('technique').value='breath';elements.get('technique').listeners.change();
    assert.equal(speech.length,2,'choosing a technique is silent');
    assert.equal(elements.get('voice').disabled,true);
    elements.get('voice').checked=true;elements.get('start').listeners.click();assert.equal(speech.length,2,'pending book text must never speak the old guide');
    elements.get('reset').listeners.click();
    elements.get('technique').value='vbt-10';elements.get('technique').listeners.change();
    elements.get('voice').checked=true;elements.get('voice').listeners.change();
    elements.get('start').listeners.click();assert.equal(speech.length,3);assert.match(speech[2].text,/While being caressed/);
    assert.equal(elements.get('technique').disabled,true);
    elements.get('technique').value='gaze';elements.get('technique').listeners.change();
    assert.equal(JSON.parse(data.get(KEY)).session.technique,'vbt-10','active session technique is locked');
    elements.get('start').listeners.click();elements.get('start').listeners.click();assert.equal(speech.length,3);
    await import('./app.js?technique-reload');assert.equal(speech.length,3);
    assert.equal(elements.get('mantra-title').textContent,'Become the caress');
    assert.equal(JSON.parse(data.get(KEY)).startDate,originalDate,'technique changes preserve daily progression');
    elements.get('reset').listeners.click();assert.equal(elements.get('technique').disabled,false);
    elements.get('start').listeners.click();assert.equal(speech.length,4,'a new session has one new opening');
    elements.get('reset').listeners.click();
    elements.get('library-search').value='112';elements.get('library-theme').value='all';elements.get('library-format').value='all';
    elements.get('browse-techniques').listeners.click();assert.equal(elements.get('library-dialog').open,true);
    assert.equal(elements.get('library-count').textContent,'1 of 112 techniques');
    elements.get('library-results').listeners.click({target:{closest:()=>({dataset:{technique:'vbt-112'}})}});
    assert.equal(elements.get('library-dialog').open,false);assert.equal(elements.get('mantra-title').textContent,'Enter the space within');
    assert.equal(JSON.parse(data.get(KEY)).technique,'vbt-112');assert.equal(speech.length,4);
    elements.get('library-clear').listeners.click();assert.equal(elements.get('library-count').textContent,'112 of 112 techniques');
    elements.get('library-search').value='no-such-technique';elements.get('library-search').listeners.input();assert.equal(elements.get('library-empty').hidden,false);
    elements.get('library-clear').listeners.click();
    elements.get('library-visual').checked=true;elements.get('library-visual').listeners.change();
    assert.notEqual(elements.get('library-count').textContent,'112 of 112 techniques');
    assert.equal(elements.get('library-results').innerHTML,'');
    elements.get('library-search').value='108';elements.get('library-search').listeners.input();
    assert.equal(elements.get('library-empty').hidden,false);
    elements.get('library-clear').listeners.click();assert.equal(elements.get('library-visual').checked,false);
    elements.get('technique').value='vbt-43';elements.get('technique').listeners.change();
    assert.equal(elements.get('technique-alternative').hidden,true);assert.equal(elements.get('technique-alternative-text').textContent,'');
    elements.get('technique').value='vbt-44';elements.get('technique').listeners.change();
    assert.equal(elements.get('technique-alternative').hidden,true);assert.equal(elements.get('technique-alternative-text').textContent,'');
    assert.equal(elements.get('visual-help').hidden,true);assert.equal(elements.get('visual-content').innerHTML,'');
    elements.get('technique').value='mantra';elements.get('technique').listeners.change();
    assert.equal(elements.get('visual-help').hidden,true);assert.equal(elements.get('visual-content').innerHTML,'');
    assert.equal(elements.get('technique-context').hidden,true);
  } finally {globalThis.setInterval=realInterval;Date.now=realNow;}
});
