// Original practical introductions to traditional meditation ideas, not book quotations.
// Numbers follow the commonly circulated Reps/Osho sequence; these are not Sanskrit verse numbers.
// Each record: number | name | theme | format | focus | prepare | attend | continue | note.
const records = `
1|Between two breaths|Breath|Seated|Notice the quiet turning of a natural breath.|Sit comfortably and allow your breathing to settle without changing its speed.|Follow an inhale, noticing the tiny natural pause before the exhale begins.|If attention wanders, return to the next breath and its effortless transition.|Do not hold your breath or manufacture a gap. Simply follow breathing if no pause is noticeable.
2|The turning breath|Breath|Seated|Follow the curve where breathing changes direction.|Choose a comfortable seat and notice the movement of breathing in your body.|Attend to the turning from inhaling to exhaling, then from exhaling to inhaling.|Follow these changes as one continuous movement rather than counting separate breaths.|Keep the breath natural; this is observation, not a breathing exercise.
3|The meeting of breaths|Breath|Seated|Notice the still center where breathing changes direction.|Let your posture be easy and feel a few ordinary breaths.|At the meeting of inward and outward movement, notice the quiet awareness of the transition.|Rest in that awareness rather than following the movement away; return gently at the next transition.|Do not lengthen the transition or wait for a special sensation. This center is an attentional image.
4|The unforced pause|Breath|Adapted|Observe stillness after a breath completes.|Sit with your feet or body supported and breathe normally.|When an inhale or exhale naturally finishes, notice any moment of quiet.|Allow breathing to resume whenever it wants, returning gently after distractions.|Gentle adaptation of a breath-pause practice: no deliberate breath retention is instructed here.
5|Light at the brow|Seeing|Visualization|Imagine gentle brightness opening above the brow.|Close your eyes softly and relax your forehead and jaw.|Bring light attention between the eyebrows; imagine subtle breath filling the head and opening into a shower of light above it.|Let thoughts pass without following them, returning to the imagined brightness with no effort to make it real.|This simplifies subtle-body imagery. Do not cross your eyes, strain, or manipulate your breathing.
6|Breath in everyday life|Breath|Everyday|Keep a little awareness of breathing during an ordinary activity.|Choose something simple and safe, such as sitting with tea or slowly tidying a table.|Do the activity while lightly noticing the transitions of your natural breath.|When you forget, reconnect for one breath and continue the task with ease.|Keep necessary attention on the activity. Do not divide attention while driving or using machinery.
7|The threshold of sleep|Breath|Bedtime|Let subtle breath awareness accompany falling asleep.|Lie comfortably when you are already ready for sleep.|Imagine the breath as a gentle movement from the brow toward the heart.|Allow the image to fade as sleep approaches, without trying to remain in control.|Use a short timer or no gong. This is a bedtime adaptation, not a promise of dream control.
8|Devotion at the breath junctions|Breath|Seated|Meet each change of breath with wholehearted attention.|Sit comfortably and let breathing be ordinary.|Notice the end of inhaling and the end of exhaling with an attitude of care.|At a transition, notice the awareness that knows the breath, then return with warmth when attention drifts.|The emphasis is devotion and knowing the breath, not breath holding or a special achievement.
9|Resting without doing|Body|Adapted|Explore stillness while the body is fully supported.|Lie on a comfortable surface and let your arms and legs rest naturally.|Release unnecessary effort while remaining aware of breathing and contact with the surface.|Notice impulses to move; adjust when needed, then return to easy stillness.|Gentle adaptation of a group of stopping practices. Breathe freely and never force immobility.
10|Awareness of gentle touch|Body|Everyday|Let a simple touch fill attention.|Rest one hand lightly on your opposite forearm, or notice the contact of soft fabric.|Attend to warmth, pressure, and texture without building a story about them.|Let attention stay with the changing sensation, returning whenever thoughts take over.|Self-touch is enough. If another person is involved, their comfortable, ongoing consent matters.
11|Quieting the senses|Body|Adapted|Notice subtle sensation when external activity settles.|Sit in a quiet place and close your eyes if comfortable.|Let sounds remain in the background and notice small sensations in the hands or body.|Allow these sensations to appear and disappear without trying to amplify them.|Gentle adaptation: do not block breathing or seal sensory openings to provoke sensations.
12|Supported lightness|Body|Seated|Let support replace the effort of holding yourself up.|Sit in a stable chair or lie on a comfortable surface.|Feel the surface carrying your weight and soften the muscles you do not need.|Notice whether a sense of ease or lightness appears, without demanding it.|Keep actual support throughout. Lightness is a felt quality, not a requirement to lose body awareness.
13|Colors dissolving into space|Seeing|Visualization|Let a five-color image soften into openness.|Close your eyes and imagine five colored circles, like the eyes in a peacock's tail, suspended in open space.|Let them suggest the five senses, then allow their outlines and colors to soften inward.|When the image fades, rest briefly without replacing it, then return to the room.|A faint image is enough. This is symbolic imagery; you do not need to make colors appear physically.
14|A fine inner thread|Body|Visualization|Imagine a delicate line through the body's center.|Sit upright without stiffness and keep breathing freely.|Picture a fine, hollow thread running gently through the center of the spine.|Rest attention along that imagined line, letting it become subtle and spacious.|This is contemplative imagery. Do not force posture or attempt to move a physical substance.
15|An inclusive inner space|Seeing|Adapted|Let a small inner focus open into spaciousness.|Sit in a quiet place with eyes gently closed and hands resting comfortably.|Bring light attention behind the brow; imagine a small point becoming less bounded.|Let the point dissolve into an inclusive field of experience, then return to ordinary bodily contact.|Gentler substitute for a head-opening closure practice. Keep nose and mouth unobstructed; do not press the eyes or seal openings.
16|The heart as a meeting place|Feeling|Visualization|Let sensory experience gather in a quiet heart space.|Sit comfortably and notice the center of your chest without changing your breath.|Imagine sounds, sights, and touch gently meeting in a spacious place there.|Rest with a feeling of receptivity rather than trying to exclude the senses.|The heart here is a contemplative image, not a claim about a physical organ.
17|The middle between thoughts|Awareness|Seated|Rest without taking either side of a mental movement.|Notice two ordinary thoughts or opposing preferences while comfortably seated.|Let go of following either one, noticing the quiet middle rather than choosing a side.|If another thought arrives, allow it to pass and return to this uncommitted attention.|The middle is experiential, not a point to locate in the head. Do not force the mind to become blank.
18|A loving gaze|Seeing|Seated|Meet one ordinary thing with gentle attention.|Place a flower, leaf, or familiar object comfortably in view.|Look with affection, letting attention settle in the object rather than moving on to another.|Stay with its center or whole presence without analysis, returning gently when attention wanders.|Keep the eyes soft and blink naturally. There is no need to stare or make the object disappear.
19|Finding your seated center|Body|Adapted|Feel balance through your seat.|Sit on a stable chair or cushion with whatever support your body needs.|Notice the contact beneath your sitting bones and the natural balance of your torso.|Let attention rest in this grounded center while breathing continues freely.|Adapted from an unsupported sitting practice. Keep feet and hands supported as needed; do not balance precariously.
20|The stillness within swaying|Body|Everyday|Notice a quiet center within gentle movement.|While safely seated, allow a very small, comfortable sway of the torso.|Follow the movement as it gradually becomes smaller, without pushing its range.|As the body settles, notice the awareness that was present throughout the motion.|Practice seated on stable ground. Do not do this while driving or when movement causes dizziness.
21|A point of sensation|Body|Adapted|Explore focused sensation without creating pain.|Rest your fingertip gently against your palm.|Feel the precise area of contact, including its center, edges, and changing intensity.|Release the touch and notice the difference, staying with awareness for a few breaths.|The traditional motif involves piercing. This adaptation uses harmless touch: never puncture skin or induce pain.
22|Watching a memory|Awareness|Seated|See a past scene as something appearing now.|Choose an ordinary, emotionally manageable memory.|Notice its images and the remembered version of yourself as a scene in awareness.|Let the scene fade and return to present sensations in the room.|Choose a neutral memory, not a traumatic event. This is observation, not an attempt to erase experience.
23|One object, the rest set aside|Seeing|Seated|Notice a chosen object and what attention leaves out.|Look gently at one ordinary object and give it your attention.|Notice how other objects recede from attention, while the chosen one remains present.|Then release both the focus on that object and the sense of excluding the others; rest openly.|Objects need not vanish from sight. This concerns attention, and differs from watching an afterimage fade.
24|Feeling without the story|Feeling|Everyday|Notice the feeling beneath liking or disliking.|When a mild reaction to someone arises, pause in a comfortable, private moment.|Set aside the story about the person and notice the reaction as bodily feeling.|Allow its texture and intensity to change without acting it out or suppressing it.|Begin with mild feelings. Reflection does not require ignoring boundaries or accepting harmful behavior.
25|Pause before an action|Body|Everyday|Meet an ordinary impulse before following it.|While safely sitting, notice an impulse to reach for something or change position.|Pause the action briefly while continuing to breathe, and feel the impulse itself.|Then choose whether to act, staying aware as movement resumes.|Never abruptly stop a movement that requires balance or attention for safety.
26|Setting down a desire|Awareness|Seated|Feel a small desire, then release its immediate demand.|Notice an everyday wish, such as checking a notification.|Feel the wish clearly without judging it or rushing to satisfy it.|For a moment, let go of the plan to obtain it and observe what remains.|Use a minor desire. This is not an instruction to ignore hunger, medication, or other genuine needs.
27|Rest after movement|Body|Adapted|Notice the transition from activity into rest.|Walk or stretch gently for a short, comfortable period.|Come to a gradual stop and sit or lie down with support.|Feel the movement settling through your body while attention stays awake.|Gentle adaptation: do not exercise to exhaustion or collapse onto the ground.
28|Letting effort fade|Body|Visualization|Explore awareness when imagined strength or certainty falls away.|Sit with your body fully supported and breathing comfortably.|Imagine effort gradually becoming unavailable, or a familiar explanation no longer being there, without making either happen physically.|Notice what is aware of that imagined absence; release the picture and feel the support beneath you.|This is an imaginative adaptation. Do not deprive yourself of sleep, food, breath, or physical strength.
29|A moment of devotion|Feeling|Seated|Let affection or reverence gather attention.|Choose a person, ideal, natural place, or sacred presence toward which you feel sincere warmth.|Rest with appreciation without asking for an outcome or trying to prove a belief.|Let the object become less important than the quality of wholehearted attention.|No particular religious belief is required. Choose something that does not create pressure or obligation.
30|The body from within|Body|Seated|Notice the lived body rather than its appearance.|Close your eyes if comfortable and feel the contact of your body with its support.|Move attention slowly through the body, noticing warmth, pressure, movement, or neutrality.|Let the separate areas become one field of changing sensation.|This is an adaptation of inward contemplation; there is no need to visualize internal organs accurately.
31|The space inside a bowl|Space|Seated|Attend to the opening rather than the container.|Place an empty bowl or cup where you can see it easily.|Notice the open space it holds, allowing the rim and material to remain secondary.|Keep an easy gaze and rest with the experience of openness.|Use an ordinary empty container. No fixed stare or special object is needed.
32|Seeing afresh|Seeing|Everyday|Look at something familiar without its usual label.|Choose a leaf, hand, cup, or other ordinary object.|Notice its actual color, shape, texture, and light as though you have not seen it before.|When a name or judgment arrives, return to what is visible now.|The practice is renewed curiosity, not trying to forget what the object is.
33|An open-sky gaze|Space|Everyday|Let the openness of the sky soften narrow attention.|Sit safely where part of an open sky is visible.|Rest your gaze on a comfortable area of sky and notice its spaciousness.|Allow sensations and thoughts to come and go within the same relaxed attention.|Never look at the sun or bright glare. A view through a window is sufficient.
34|Listening with your whole attention|Sound|Everyday|Receive a teaching without silently preparing a reply.|Choose a short, thoughtful passage spoken aloud by yourself or another person.|Listen to its meaning and sound, noticing the urge to agree, argue, or anticipate.|Let those reactions pass and return to receiving the next phrase clearly.|Gentle adaptation: blink freely and relax the eyes rather than attempting unblinking attention.
35|Looking into depth|Seeing|Adapted|Explore visual depth from a safe position.|Choose a photograph of a deep landscape or a view from a secure indoor place.|Notice foreground, distance, and the space between them without leaning or straining.|Let attention rest in the sense of depth, then soften into the whole view.|The traditional motif uses a well. Do not approach wells, cliffs, water edges, or other hazards for this practice.
36|Letting a visual impression fade|Seeing|Seated|Follow the transition from seeing to remembering to quiet.|Look softly at one object for a few natural breaths.|Close your eyes and observe its mental impression without trying to sharpen it.|Let that impression fade and notice the awareness that remains.|Do not strain for an afterimage or look at bright lights.
37|From a syllable to a feeling|Sound|Visualization|Let an imagined syllable become increasingly subtle.|Choose a simple syllable and imagine it resting lightly in awareness.|First picture its shape, then attend to its imagined sound, and then to its felt quality.|Let these supports grow faint and rest without repeating them for a moment.|A simplified adaptation of a mantra-visualization practice; no specialized placement or initiation is implied.
38|The center of sound|Sound|Seated|Let a continuous sound gather your attention.|Sit comfortably near a steady, gentle sound such as rainfall, flowing water, or a quiet recording.|Receive the sound as one continuous field, without naming each part or following a story.|Notice the listening presence at the center of the experience; return there when attention wanders.|Ordinary surrounding sounds are an accessible alternative. No need to block the ears; turn off app music if it competes with listening.
39|A sound fading into silence|Sound|Seated|Follow one comfortable tone into its ending.|Sit easily and make one quiet, unforced hum or familiar mantra sound on an ordinary exhale.|Listen to the vibration as it becomes softer and ends naturally.|Stay with the silence afterward, then repeat when breathing feels ready.|Keep the sound gentle and the breath comfortable; do not prolong either through effort.
40|Before and after a sound|Sound|Seated|Notice the quiet on either side of a syllable.|Choose a short syllable and become aware of the silence before saying it.|Speak it softly, listening to its beginning, body, and ending.|Notice the silence after it, without immediately filling that space with another sound.|A few repetitions are enough before resting quietly. Avoid forcing a perfectly silent mind.
41|The resonance of strings|Sound|Seated|Hear the blended resonance within an instrumental tone.|Choose a quiet passage of sustained string music, such as a tanpura or bowed string, at a comfortable volume.|Listen to the combined resonance and overtones as one sound rather than following the tune.|Remain with that blended sound and its gradual fading; let the listening become unhurried.|The source specifies stringed instruments. Other sustained tones are an adaptation; the app's ambient music is synthesized.
42|From spoken sound to inner sound|Sound|Seated|Let a repeated sound become quieter.|Choose a short, comfortable mantra or syllable and say it softly a few times.|Gradually reduce the volume until the repetition is only imagined.|Let even the inner repetition fade, resting in the quiet it leaves.|Never force the breath. The optional opening voice is separate from this self-led practice.
43|Resting attention on the tongue|Body|Seated|Notice the quiet center of the tongue.|Let the jaw relax and the mouth open a little, only as far as is comfortable.|Rest light attention at the middle of the tongue without pressing, curling, or stretching it.|Keep breathing freely and return to this small area when thought carries attention away.|An alternative breath-and-sound approach is described in the source note. Choose one approach for a session.
44|The vowel within Aum|Sound|Seated|Attend to the middle vowel of A-U-M.|Sit comfortably and silently recall Aum as three parts: A, U, and M.|Let the opening A and closing M fall away; attend only to the rounded U, like a gentle oo sound.|Imagine that vowel, or sound it softly on an easy exhale, then let it fade before repeating.|This follows the Reps/Osho sound formulation. Sanskrit readings differ; do not substitute an arbitrary mantra or force a long tone.
45|The silent ending of ah|Sound|Seated|Follow an inwardly spoken ah into its quiet ending.|Sit comfortably and mentally say a syllable ending in ah, without needing to voice it aloud.|Notice the imagined vowel softening into its final breath-like h quality.|Let even that subtle inner sound fall away, remaining quietly attentive before another repetition.|Keep physical breathing natural. This is silent attention to an ending, not a forced whisper or exhalation.
46|Listening inward|Sound|Adapted|Explore quiet listening without physical pressure.|Sit somewhere quiet with your ears and breathing unobstructed.|Let external sounds recede into the background and notice any subtle sound or stillness already present.|Rest with what is actually heard, without trying to generate a special inner tone.|Adapted from a practice involving ear closure and muscular contraction. Those physical techniques are not instructed here.
47|Hearing your own name|Sound|Seated|Let the sound of a name open into listening.|Say your name quietly once and listen to its syllables.|Repeat it slowly a few times, setting aside the personal history associated with it.|Let the name fade, then include other sounds in the same listening awareness without choosing between them.|Use any name that feels comfortable. Stop repeating when it becomes mechanical.
48|Awareness in intimacy|Feeling|Adult context|Attend to the beginning of intimacy without chasing a result.|In an existing, mutually desired private moment between consenting adults, communicate comfort and boundaries.|Notice the first felt warmth and aliveness of intimacy instead of rushing toward an ending.|Remain attentive to that present experience and each other; either person can pause or stop at any time.|A non-graphic adaptation of a sexual-union practice, not a full sexual technique. A timer is optional; consent and comfort take priority.
49|Allowing natural movement|Body|Adult context|Notice spontaneous movement during a welcome embrace.|In a consensual embrace, remain comfortable and aware of your own balance and boundaries.|Notice any natural trembling or movement without deliberately intensifying it.|Allow the movement to settle and stay present to what both people communicate.|This describes an intimacy-related motif without prescribing sexual technique. Never induce shaking or override discomfort.
50|Remembered closeness|Feeling|Adult context|Explore the felt warmth of a welcome memory.|While alone, bring to mind a gentle memory of consensual closeness that feels comfortable now.|Let the details of the scene recede and notice its present feeling in the body.|Stay with that warmth while it lasts, allowing the memory and feeling to fade.|Choose a welcome, non-distressing memory. This is a private contemplation, not an instruction to recreate an experience.
51|Rest in joy|Feeling|Everyday|Give a genuine moment of happiness your full attention.|Begin when joy is already present, such as after meeting someone dear.|Let the story recede and notice how the happiness feels right now.|Rest with the feeling while it is present, allowing it to change naturally.|No need to manufacture happiness. Choose another practice if joy is not present today.
52|Tasting completely|Body|Everyday|Let a small taste fill attention.|Take a comfortable sip of water or a small bite of familiar food while seated.|Notice taste, temperature, and texture before swallowing normally.|Pause afterward to notice how the sensation changes and fades.|Eat and swallow normally. Do not hold food in your mouth for the timer or interfere with swallowing.
53|Knowing that you are sensing|Awareness|Everyday|Notice being aware while enjoying a sensory experience.|Choose an easy activity such as softly singing, looking at a plant, or tasting a little food.|Enjoy the sensory detail while also noticing the simple sense that you are present and aware.|When absorbed in commentary, return to both the experience and this felt presence.|Let this remain light. It does not require splitting attention into two rigid parts.
54|Savoring satisfaction|Feeling|Everyday|Rest with the feeling that something is enough.|Notice a small moment of satisfaction, perhaps after finishing a simple task.|Set aside what caused it and attend to the felt ease of no longer reaching for something.|Allow that ease to be present without trying to keep it permanently.|This differs from chasing pleasure: begin with satisfaction that is actually available.
55|The edge of sleep|Awareness|Bedtime|Notice waking giving way to sleep.|Lie comfortably at your normal bedtime and allow the day to recede.|Observe the softening of thoughts and sensations as drowsiness arrives.|Let sleep happen rather than trying to capture the exact transition.|Turn off the gong if you intend to sleep. Do not sacrifice rest to remain watchful.
56|Seeing through appearances|Awareness|Contemplation|Notice how labels divide a continuous experience.|Look at a familiar scene and notice the names you give its parts.|For a few breaths, set those names aside and receive colors, shapes, and sounds together.|Compare the direct experience with the separate categories your mind adds.|An inquiry into perception, not a demand to deny practical reality or ordinary responsibilities.
57|Steadiness within wanting|Feeling|Everyday|Make room around a strong but manageable wish.|Sit safely and notice a desire that is present without acting on it immediately.|Feel its bodily energy while keeping contact with your seat and breath.|Let it rise or fall, recognizing that awareness need not follow every impulse.|Start with manageable desires. Attend to real needs and seek support for urges that feel unsafe.
58|Life as a passing scene|Awareness|Contemplation|Meet present experience as a changing display.|Sit comfortably and receive the sights, sounds, and thoughts of this moment.|Imagine the whole experience as a scene unfolding, without getting caught in one role or story.|Let the scene continue changing while remaining aware of the room and your bodily support.|The scene is a contemplative metaphor, not a claim that real people or responsibilities do not matter.
59|Between pleasure and discomfort|Feeling|Contemplation|Notice awareness around opposite preferences.|Bring to mind one mildly pleasant and one mildly unpleasant experience.|Notice how the mind leans toward one and away from the other.|Let both images recede and rest with the awareness that noticed the two movements.|Do not create discomfort. The exercise uses mild, remembered contrasts.
60|Recognizing shared impulses|Feeling|Contemplation|Meet ordinary human tendencies with understanding.|Notice a familiar desire or reaction in yourself.|Consider that other people also experience wanting, fear, affection, and uncertainty.|Let this recognition soften judgment while keeping clear choices about your behavior.|Acceptance of an impulse is different from acting on it or excusing harm.
61|A wave within a larger movement|Space|Visualization|Explore the image of a wave belonging to water.|Sit comfortably and picture one wave rising and settling in an ocean.|Notice that its temporary shape never separates it from the water.|Let the image suggest how your changing experience belongs within a larger life.|Use the image as a contemplation, not something you must believe or vividly see.
62|Where attention already is|Awareness|Seated|Begin with the actual location of attention.|Sit quietly and notice whether attention is on a sound, sensation, image, or thought.|Instead of immediately moving it, become curious about that experience as it is.|When attention moves again, notice its new resting place with the same openness.|This is not an invitation to feed a distressing thought; return to physical contact if needed.
63|Awareness through one sense|Awareness|Seated|Let clear sensation reveal the knowing of it.|Choose one uncomplicated sensation, such as the feel of your hands touching.|Notice its texture and then the simple fact that it is being experienced.|Remain with both sensation and knowing without explaining them.|When the sensation changes, let it change; vividness is not required.
64|A sudden moment of presence|Awareness|Adapted|Notice an ordinary surprise after it has safely occurred.|Recall a harmless surprise, or notice a spontaneous everyday interruption while safely seated.|Observe the instant when the usual stream of thought briefly pauses.|Rest for a breath in that freshness, then continue normally.|Adapted from intense transition examples. Do not create fear, danger, hunger, or physical shocks to practice.
65|Before judging pure or impure|Awareness|Contemplation|Look at the labels added to a neutral experience.|Choose an ordinary object or harmless everyday preference.|Notice judgments of acceptable, unacceptable, better, or worse as thoughts.|Let those labels recede briefly and return to direct perception.|This questions mental labels, not hygiene, consent, ethical responsibility, or practical safety.
66|Equal regard|Feeling|Contemplation|Keep an even quality of attention through changing social feelings.|Bring to mind a friend and a difficult person, choosing only manageable examples.|Notice the differences, then explore the same steady awareness of each; also notice your response to remembered praise or criticism.|Let attraction and resistance settle without forcing equal affection or deciding whose judgment is true.|Equal regard does not require equal trust, access, or closeness. Use a stranger instead if a difficult person feels overwhelming.
67|Change noticing change|Awareness|Seated|Watch experience continually renewing itself.|Sit quietly and choose a changing sensation such as breathing or sound.|Notice how no single moment remains exactly as it was.|Include thoughts and feelings in the same observation, returning whenever you grasp at one.|The task is noticing change, not making everything disappear.
68|Gentle care for attention|Awareness|Everyday|Hold a small activity with patient care.|Choose a simple task, such as folding a cloth or preparing a cup.|Stay close to each movement and decision as if caring for something delicate.|When attention wanders, return kindly to the next small part of the task.|Keep the activity natural. Careful attention need not become perfectionism.
69|Loosening the story of bondage|Awareness|Contemplation|Notice the concepts of being stuck and being free.|While comfortably seated, notice any thought that says your meditation must achieve a special state.|Recognize both the problem-image and the imagined solution as thoughts arising now.|Let both rest for a few breaths, without requiring a verdict.|A philosophical inquiry; it does not deny real constraints or replace practical action.
70|A line of light through the spine|Seeing|Visualization|Imagine a fine line of brightness rising through your center.|Sit with the spine comfortable and the breath unforced.|Picture soft brightness rising along the central axis from the base toward the crown, becoming finer as it rises.|Let it soften into the space above the head, then release the image and feel the whole supported body.|A simplified subtle-body visualization, not physical anatomy. No specific chakra map, forced energy, or breath control is required here.
71|Small flashes of brightness|Seeing|Visualization|Imagine brightness linking successive inner centers.|Close your eyes comfortably and picture the body's central axis.|Imagine gentle, brief connections of light between successive points along it, moving upward.|Let the imagined light become subtle above the head, then release the picture and return to bodily contact.|This simplifies traditional lightning imagery. Use no flashing screen, breath retention, muscle locking, or visual strain.
72|A luminous world|Seeing|Visualization|Imagine ordinary surroundings permeated by aliveness.|Look softly at the room or a natural view.|Imagine a transparent brightness within the scene, including your own body.|Let the image become less distinct while maintaining a receptive awareness of the whole.|This is an imaginative contemplation, not a claim that you should literally see a glow.
73|Clarity of a wide sky|Space|Everyday|Meet open sky without filling it with commentary.|Sit somewhere safe with an easy view of a broad, clear part of the sky.|Let the gaze relax and notice the uninterrupted field rather than searching for objects.|Allow your attention to feel similarly open for a few breaths.|Avoid sun and glare. You can use a remembered sky when no comfortable view is available.
74|A spacious inner sky|Space|Visualization|Imagine openness where the head usually feels bounded.|Sit comfortably with the face and forehead relaxed.|Picture a broad, clear space rather than a tightly enclosed interior of the head.|Let sounds and thoughts appear within that imagined openness without crowding it.|A visualization, not an anatomical claim. Return to room sounds if it feels disorienting.
75|Light through changing states|Seeing|Contemplation|Contemplate awareness as light through waking, dreaming, and sleep.|During a calm waking moment, imagine a quiet luminosity as a symbol of awareness.|Recall waking, dreaming, and deep sleep as changing states, and contemplate this light as their common background.|Release the image and remain with present experience; let sleep occur normally when bedtime comes.|A daytime contemplation of traditional imagery, not a claim that you must stay conscious in deep sleep or control dreams.
76|Resting with darkness|Seeing|Everyday|Let a comfortable dim setting become the focus.|Sit in a familiar, safely arranged room with low light.|Allow your eyes to adapt and notice darkness as an experience rather than a problem.|Receive faint sounds and sensations while resting without searching for shapes.|Do not walk around in darkness. Use ordinary lighting instead if darkness feels unsettling.
77|Darkness behind closed eyes|Seeing|Seated|Carry a gentle sense of darkness into an open-eyed view.|While seated in a safe, softly lit place, close your eyes and notice the dark visual field.|Rest with whatever darkness or faint impressions are actually present, without pressing the eyes.|Open the eyes gently and retain a light imaginative sense of that dark spaciousness alongside the visible room.|Do not try to black out vision or obscure real surroundings. Stop the image and reorient if it feels uncomfortable.
78|Staying where attention lands|Awareness|Everyday|Give one present experience your full, gentle attention.|Notice a sound, texture, or sight that naturally attracts you.|Pause and experience it directly instead of immediately naming or following it.|Stay for a few breaths, then release it without needing a result.|Choose an ordinary, comfortable focus rather than a distressing or overwhelming stimulus.
79|Imagining the body dissolving|Seeing|Adapted|Explore letting go through symbolic imagery.|Sit securely with an easy sense of the room around you.|If comfortable, imagine the body's outline gradually dissolving into light, from feet upward.|Let the image fade and return to the actual contact of your hands and seat.|Adaptation of fire imagery. No real fire or harm is involved; skip this if dissolution imagery feels unsettling.
80|Imagining the world dissolving|Space|Adapted|Let a mental picture of the world gently fall away.|Sit in a familiar, quiet place and picture an ordinary landscape.|Imagine its details softly dissolving into open space, leaving no need to hold the picture.|Release the visualization and notice the real surroundings again.|Adaptation of symbolic burning imagery. Never involve actual fire; keep this brief if it feels disorienting.
81|From parts to a whole|Awareness|Contemplation|Let layers of meaning return to the awareness knowing them.|Read a short sentence: notice letters joining into words and words into meaning.|Consider the same movement from objects to the world and to the ideas through which you understand it.|Let these increasingly broad layers resolve into the present act of knowing, then release the conceptual exercise.|An introductory adaptation of a layered cosmological contemplation, not a complete teaching of its traditional categories.
82|Including thoughts and body|Body|Seated|Let different aspects of yourself share one field of attention.|Sit comfortably and notice a bodily sensation, a thought, and the feeling of being you.|Allow all three to be present without deciding which is the real self.|Let attention broaden to include changing experiences together.|Include only what is available; do not strain to feel internal organs or create an identity-free state.
83|Before a wish forms|Awareness|Contemplation|Explore the sense of self before wanting or knowing something.|Sit and allow a small wish or recognition to arise naturally.|Ask quietly: before this desire or this knowledge, what lets me say that I am?|Let the question and any answers settle; remain with immediate experience rather than searching for a definition.|You do not need to catch every thought or find a permanent blank state. The question is an inquiry, not a denial of existence.
84|Awareness beyond the body outline|Space|Visualization|Explore spaciousness while keeping the body grounded.|Sit with clear contact through feet or seat.|Include sounds and space around the body as well as sensations within it.|Let the usual boundary soften in imagination while remaining oriented to the room.|This is a contemplation, not an instruction to neglect the body. Return to contact points if disoriented.
85|Resting without a chosen object|Awareness|Seated|Allow attention to be open rather than fixed.|Sit comfortably and first settle with a few ordinary breaths.|Let go of selecting a special sound, image, or thought to concentrate on.|Allow experience to appear and disappear while resting without a deliberate target.|Do not suppress thoughts. Open attention includes their arrival and passing.
86|Beyond something to grasp|Awareness|Contemplation|Notice the limits of trying to make awareness an object.|Ask inwardly what is aware of this moment, without expecting a verbal answer.|Notice each answer, image, or explanation as another experience being known.|Let the search relax and simply remain present for a few breaths.|A subtle inquiry. Returning to breath or sound is always an available starting point.
87|Presence in ordinary thoughts|Awareness|Contemplation|Look beyond the boundaries carried by everyday self-statements.|Notice a simple thought of existing, owning something, or identifying an object.|Feel how its words draw a boundary around self, possession, or thing; notice the awareness of the words as well.|Let the statement fall quiet and explore awareness without that particular boundary for a moment.|Keep ordinary responsibilities and distinctions. This is contemplation, not an instruction to reject practical ownership or identity.
88|Knowing and what is known|Awareness|Contemplation|Explore experience without rigidly separating observer and object.|Look at one ordinary object and notice the act of seeing.|For a moment, attend to the object and the knowing of it as one present event.|Rest without deciding whether awareness is inside or outside you.|This is experiential inquiry, not a claim that people or things lack independent practical importance.
89|Including the whole moment|Awareness|Seated|Let breath, body, and mind belong in the same awareness.|Sit comfortably and notice breathing, bodily contact, and whatever thoughts are present.|Allow these experiences to coexist instead of choosing one and pushing the others away.|Return to this inclusive attention whenever you notice yourself narrowing around a single thought.|Nothing needs to disappear for the practice to be happening.
90|Softness around the eyes|Body|Adapted|Let facial ease spread through the body.|Close your eyes gently and relax the muscles around them.|Notice whether that softness is also felt in the jaw, chest, and hands.|Rest with the whole-body feeling of easing rather than trying to intensify it.|Gentle adaptation of a touch motif: do not press, rub, or touch the eyeballs.
91|Space above and below|Space|Visualization|Imagine openness extending beyond the body's height.|Sit with stable physical support.|Picture spaciousness above the head and below the feet at the same time.|Let attention include both directions without traveling away from the present room.|Keep breathing natural and remain aware of contact with the seat.
92|Three areas of openness|Space|Visualization|Let attention soften above, below, and at the heart.|Sit comfortably and imagine a little open space above and below you.|Include a third area of gentle openness at the center of the chest.|Hold these lightly together, then release the picture and rest.|The locations are imaginative supports, not instructions to manipulate physical organs or energy.
93|Space within one sensation|Body|Visualization|Imagine spaciousness inside a small part of the body.|Choose a comfortable area, such as the palm of one hand.|Notice its sensations and imagine room around and within them.|Let the sense of spaciousness expand without losing the actual feeling of the hand.|Use a neutral area rather than an injury or a painful site.
94|Space throughout the body|Body|Visualization|Imagine every part of the body pervaded by spaciousness.|Sit comfortably and notice the body as a whole.|Imagine skin, muscle, bones, and the body's interior sharing the same open quality as the space around you.|Rest with that undivided spaciousness briefly, then let the image go and feel your actual support.|Traditional space or cosmic-essence imagery, not a claim about body composition. No need to picture anatomy in detail.
95|Creative warmth in the chest|Feeling|Visualization|Explore a gentle feeling of creative possibility.|Sit comfortably and notice the chest area without pressing or controlling it.|Imagine a soft warmth associated with creating, caring, or bringing something into life.|Let that felt quality spread naturally, or simply remain with its absence if nothing appears.|A non-sexual adaptation of a traditional creative-energy image; no special body sensation is required.
96|An unobstructed view|Space|Everyday|Rest attention in an open landscape.|Choose a safe place with an easy view of open space, such as a park or distant horizon.|Let the gaze be broad rather than searching for something to examine.|Notice thoughts moving within the same openness as sounds and bodily sensations.|Stay in a secure location and avoid sun glare. A window view can work.
97|The world as a field of ease|Space|Visualization|Imagine the surrounding space as continuous with ease in the body.|Notice any small area of comfort, even if the rest of the body feels neutral.|Imagine that quality gently extending into the space around you.|Let the image soften and receive the whole scene without grasping at the feeling.|There is no need to create bliss. A subtle sense of ease is sufficient.
98|Resting in the chest's center|Feeling|Seated|Notice the quiet area between the armpits.|Choose any comfortable, supported posture.|Bring gentle attention to the broad center of the chest and soften unnecessary effort there.|Let awareness remain with breathing and contact in this area without demanding calm.|Do not change breathing or press the chest. If this focus is uncomfortable, use the hands instead.
99|Awareness in every direction|Space|Visualization|Let attention include front, back, and both sides.|Sit with a stable sense of your body's position.|Listen around you, then imagine awareness extending equally in every direction.|Rest with that inclusive field rather than moving attention from point to point.|Keep a clear sense of the actual room and return to bodily contact whenever needed.
100|Remembering the experiencer|Awareness|Everyday|Stay aware of yourself while engaging with something.|Look at a pleasant object or listen to an ordinary sound.|Notice the experience while also recognizing that it is being known here and now.|Let enjoyment continue without becoming completely lost in commentary about it.|This is light self-remembering, not continuous self-monitoring or withdrawal from life.
101|Contemplating boundless awareness|Awareness|Contemplation|Explore traditional images of awareness without a narrow boundary.|Sit quietly and consider the idea that awareness is more spacious than a single thought or role.|Let the image expand beyond your usual self-description without claiming special personal powers.|Release the words and return to the simple fact of being aware.|Traditional language about all-knowing or all-powerful consciousness is symbolic contemplation, not a claim about your abilities.
102|The same presence within and around|Space|Visualization|Imagine inner and outer experience sharing one field.|Notice bodily sensation, then the sights and sounds around you.|Imagine the same quality of presence pervading both, without a hard dividing line.|Let the picture fade while retaining an easy awareness of the whole moment.|An exploratory image, not a belief you must adopt.
103|The beginning of wanting or knowing|Awareness|Everyday|Notice an experience as it first forms.|While seated quietly, wait for a small intention or recognition to arise on its own.|Attend to its earliest felt movement before it becomes a detailed story.|Let it develop or fade naturally, then rest until another appears.|Do not manufacture an urge or try to stop all thought.
104|One perception within a wider field|Awareness|Contemplation|Notice how a particular experience occupies only part of awareness.|Choose one sound or sensation and attend to it briefly.|Then include the surrounding silence, other sensations, and the space of the room.|Let the single focus take its place within that wider field.|Broaden gently; you do not need to perceive everything at once.
105|Forms within one experience|Awareness|Contemplation|Explore the relationship between separate forms and shared awareness.|Look around and notice several clearly different objects.|Without erasing their differences, notice that they appear together in one present field of experience.|Include your body's sensations in the same field, then rest.|This inquiry preserves ordinary distinctions while exploring how experience is known.
106|Recognizing awareness in others|Feeling|Contemplation|Remember that other people experience a world from within.|Bring to mind one person, then someone whose life is different from yours.|Consider that each has sensations, hopes, uncertainty, and an inner perspective.|Let this recognition support a moment of simple, respectful concern.|You cannot literally know another person's experience. Empathy does not replace asking or respecting boundaries.
107|A shared field of life|Awareness|Contemplation|Explore the image of consciousness expressed in many forms.|Observe a living scene, or imagine one with people, animals, and plants.|Consider the traditional idea that diverse life participates in a shared ground of being.|Let the concept recede and rest with attentive, respectful presence.|Treat this as philosophical contemplation, not an established scientific claim.
108|Awareness as the inner guide|Awareness|Contemplation|Contemplate the same illuminating awareness in every person.|Sit quietly and notice the awareness through which your own thoughts and actions are known.|Consider the traditional idea of that same consciousness as the inner guiding presence in every being, including yourself.|Rest in this shared presence as a contemplation, letting personal stories and explanations fall quiet.|This spiritual inquiry is not a decision-making technique or a claim to receive infallible messages.
109|The body as an open room|Body|Visualization|Imagine space inside the body's outline.|Sit or lie with the body comfortably supported.|Picture the body's outer outline as enclosing a spacious room rather than a tightly packed interior.|Let this image soften tension, then return to actual sensations and support.|Use it only as imagery; do not deny bodily needs or force a feeling of emptiness.
110|A playful field of experience|Space|Visualization|Imagine the world as open space in which mind can play.|Sit comfortably and imagine the surrounding world as a spacious, empty setting.|Notice images and thoughts moving freely in this imagined openness without having to grasp them.|Let both the movements and the setting fade, then reconnect with the real room and body.|A playful visualization, not a claim that real problems or other people are unreal or unimportant.
111|Setting down opposite answers|Awareness|Contemplation|Consider opposing descriptions, then release both.|Bring to mind knowing and not knowing; notice the concepts without choosing one as your identity.|Then consider existing and not existing in the same way, observing these as ideas rather than conclusions.|Let both pairs fall quiet for a moment and remain with immediate experience.|Keep the inquiry brief and grounded. It is not a reason to deny your existence or avoid practical decisions.
112|Resting in open stillness|Space|Seated|Release the chosen meditation support for a moment.|Settle into a comfortable posture and notice a few natural breaths.|Allow any deliberate image, phrase, or focus to fall away without pushing experience out.|Rest with open awareness, returning to bodily contact when the session ends.|Nothing special has to happen. If open attention feels vague or unsettling, use breath or sound again.
`;
export const catalogRows=records.trim().split('\n').map(line=>line.split('|'));
