// Original, concise procedural summaries of the linked Osho commentaries.
// These are not transcriptions or a replacement for the complete book.
// Each row: number, theme, setting, focus, three steps, practice note.
const rows = [
  [1,'Breath','Seated','Notice the quiet interval between natural breaths.',
    'Sit comfortably. Let breathing happen by itself, and feel the air entering and leaving your nose.',
    'Follow an inhalation inward. Notice the brief interval before it becomes an exhalation; then follow the breath outward.',
    'Notice the interval before the next inhalation. Whenever you become distracted, return to observing this natural cycle.',
    'Observe the gaps; do not hold your breath or lengthen them.'],
  [2,'Breath','Seated','Attend to the turning of the breath.',
    'Sit at ease and follow one complete breath without changing its speed or depth.',
    'Watch the precise transition as the inward breath turns outward, then as the outward breath turns inward.',
    'Keep returning to these two changes of direction, experiencing the breath as a continuous circle.',
    'The emphasis is the turning itself, rather than counting breaths.'],
  [3,'Breath','Seated','Find the still center where the two directions meet.',
    'Sit with your abdomen relaxed and let your belly move naturally as you breathe.',
    'Follow the inward movement toward the navel area. Attend to the point where inward and outward movement seem to meet.',
    'If neither direction is distinct for an instant, remain attentive to that still center, then allow breathing to continue.',
    'Do not pull the breath downward or manufacture a pause.'],
  [4,'Breath','Seated','Be aware when breathing pauses of its own accord.',
    'Sit quietly, allowing thoughts and breathing to settle without trying to achieve a special state.',
    'If a spontaneous pause occurs after an inhalation or exhalation, notice the accompanying stillness.',
    'Let the next breath arrive freely. Continue resting in awareness without trying to repeat the experience.',
    'Never create a pause through breath-holding, fright, or shock.'],
  [5,'Light & space','Seated','Attend between the eyebrows and imagine a shower of light.',
    'Close your eyes and rest attention gently in the space between your eyebrows. Let thoughts pass without following them.',
    'Become aware of the subtle feeling of breathing there, rather than concentrating on the air alone.',
    'Imagine this subtle vitality filling the head and showering down from its crown as light. Remain receptive.',
    'Use light as contemplative imagery; keep your eyes and forehead relaxed.'],
  [6,'Breath','Daily life','Keep awareness of breath intervals during simple activities.',
    'Choose an ordinary, undemanding activity, such as eating or walking in a safe, familiar place.',
    'Continue the activity while noticing the small natural intervals between inhalation and exhalation.',
    'Whenever the activity absorbs all your attention, gently rediscover the interval without stopping what you are doing.',
    'Leave breathing unchanged. Do not divide attention while driving or doing hazardous work.'],
  [7,'Rest & sleep','Lying down','Carry subtle breath awareness into sleep.',
    'At bedtime, lie comfortably. Rest attention gently at the brow, with awareness of the subtle feeling of breathing.',
    'As sleep approaches, imagine this breath vitality descending into and filling the heart area.',
    'Keep that gentle feeling as you drift off. Let sleep arrive rather than struggling to stay awake.',
    'Osho connects this with dream awareness; particular dreams or results are not guaranteed.'],
  [8,'Breath','Seated','Bring wholehearted devotion to the meeting points of breath.',
    'Sit quietly and approach this practice with devotion: offer your attention wholeheartedly, rather than mechanically observing.',
    'Follow the breath to its two natural junctions, where inhaling becomes exhaling and exhaling becomes inhaling.',
    'Let your attention settle completely at these junctions, remaining open to the awareness that knows the breath.',
    'Devotion is central to this version. Do not impose a breathing rhythm.'],
  [9,'Body & stillness','Lying down','Use stillness to witness an emotional disturbance.',
    'For the resting version, lie supported on your back and allow the body to become quiet, as if lifeless.',
    'If an ordinary feeling of anger or agitation is present, observe it without moving to express it or building its story.',
    'Remain aware as the disturbance changes. When finished, move gently and sit up in your own time.',
    'This summarizes the lying-still option. The commentary also gives separate gazing and sucking methods. Breathe freely.'],
  [10,'Love & feeling','With a partner','Become absorbed in the felt experience of loving touch.',
    'With someone you trust, receive a gentle caress that is welcome to both of you. Let the body relax.',
    'Feel the touch directly, allowing thoughts about the person, the past, or what comes next to fall away.',
    'Let attention become absorbed in the loving sensation itself, with less emphasis on a separate person receiving it.',
    'The practice concerns loving absorption, not analyzing touch. Either person can stop at any time.'],
  [11,'Body & stillness','Seated','Let outward sensory activity become quiet.',
    'Sit supported, close your eyes, and allow your body to become still without stiffening it.',
    'Imagine sight and hearing resting, as though your senses no longer reach outward. Let breathing remain free.',
    'Stay attentive to the quiet within rather than following outside impressions. Release the exercise gently.',
    'Gentle adaptation: the source includes stopping sensory openings and breath. Those physical closures are omitted here.'],
  [12,'Body & stillness','Seated or lying','Explore the feeling of weightlessness in a balanced body.',
    'Sit in a balanced, supported position or lie comfortably. Relax unnecessary muscular effort.',
    'Close your eyes and attend to the whole body. Allow the usual feeling of heaviness to soften.',
    'Imagine the body becoming light, almost without weight, while remaining quietly aware of it.',
    'This is a felt or imagined change, not an attempt to levitate or lose physical support.'],
  [13,'Light & space','Seated','Let imagined sensory colors dissolve into spaciousness.',
    'Close your eyes and imagine the five senses as five colored circles filling the space around you.',
    'Attend to the circles together, then allow them to merge and lose their separate outlines.',
    'When the colors dissolve, rest in the spaciousness remaining, without immediately creating another image.',
    'This follows the color-imagery option; the commentary also describes concentration on a single point.'],
  [14,'Body & stillness','Seated','Rest attention in a delicate thread through the spine.',
    'Sit comfortably upright, keeping your back supported if needed. Close your eyes.',
    'Imagine a very fine thread running centrally through the spine. Let attention settle within that thread.',
    'Keep the image delicate and unforced. When thoughts distract you, return to the inner thread.',
    'Attend inwardly; do not tense your back or try to force a physical sensation along it.'],
  [15,'Body & stillness','Teacher-led','Understand the method of closing the sensory openings.',
    'Read the linked commentary before attempting this method. It describes closing seven openings and gathering attention inward.',
    'Its intended focus is an inner point between the eyes as outward sensory activity is withdrawn.',
    'For physical practice, seek an experienced teacher who can explain the method and its limits. Do not block your breathing alone.',
    'Orientation only: airway closure and breath retention are not taught by this app.'],
  [16,'Love & feeling','Daily life','Receive a sensory experience through the heart.',
    'Choose a simple contact, such as touching a tree or feeling the ground beneath your feet.',
    'Let the sensation register in the heart area, rather than immediately naming or analyzing what you touch.',
    'Remain with the direct feeling, allowing it to fill your awareness and soften the sense of distance from the experience.',
    'The emphasis is feeling and absorption, not imagining facts about the object.'],
  [17,'Awareness','Daily life','Notice the middle between opposing reactions.',
    'When two opposite reactions arise, such as attraction and aversion, become aware of both.',
    'For a moment, do not take either side or try to suppress it. Notice the quiet between the two pulls.',
    'Rest in that undecided awareness, then respond to the situation with care.',
    'Explore inward balance; this does not mean avoiding necessary practical decisions.'],
  [18,'Love & feeling','Seated','Look at one object with love, without wanting to possess it.',
    'Choose an object you love looking at, such as a flower. Sit where you can see it comfortably.',
    'Give it your full, affectionate attention without demanding anything from it or planning to own it.',
    'Let everything else recede as the object fills awareness. Stay with the feeling of loving attention.',
    'Keep the eyes comfortable and blink naturally. Love, rather than visual strain, is the focus.'],
  [19,'Body & stillness','Seated','Become sensitive to the contact of sitting.',
    'Sit on a stable seat with both sitting bones supported. Arrange your posture so you do not need to brace.',
    'Feel the contact beneath your buttocks directly, bringing sensitivity to that area rather than merely thinking about it.',
    'Let the body balance over the seat and remain attentive to this grounded point of contact.',
    'Keep any support you need. Do not balance precariously or force a posture.'],
  [20,'Body & stillness','Seated','Follow a gentle swaying movement toward stillness.',
    'For the seated version, sit securely and allow your torso to sway in small, easy circles.',
    'Feel the motion from within. Gradually allow the circles to become smaller without abruptly suppressing the movement.',
    'As visible movement settles, remain attentive to any subtle inner sense of motion, then to stillness.',
    'The source also describes yielding to a vehicle’s sway as a passenger. Never practice while driving.'],
  [21,'Body & stillness','Seated or lying','Explore the center of an already-present sensation.',
    'Use only a mild, ordinary discomfort that is already present, and settle in a comfortable position.',
    'Locate the sensation carefully instead of treating the whole body as painful. Notice its precise region and qualities.',
    'Follow attention toward its center and observe how the sensation changes, without trying to intensify it.',
    'The commentary allows existing pain as an alternative to piercing. Never injure yourself or ignore pain needing care.'],
  [22,'Awareness','Lying down','Review the day backward as an observer.',
    'At bedtime, begin with the most recent event of your day.',
    'Move backward through earlier events, step by step toward waking, watching yourself as a character in a film.',
    'Notice feelings without becoming absorbed in them again. If you drift into forward storytelling, gently return to backward observation.',
    'Use ordinary memories. Stop if the review becomes distressing; there is no need to revisit traumatic events.'],
  [23,'Awareness','Seated','Absorb one object, then let the object go.',
    'Choose one object and give it sustained attention until its presence is felt, rather than merely described in thought.',
    'Let other objects recede from awareness. Close your eyes when the chosen object is vividly present inwardly.',
    'Now release that inner object too. Remain with the open awareness left behind instead of replacing it.',
    'The movement is from many objects, to one, to no object.'],
  [24,'Love & feeling','Daily life','Turn from the person who triggers a mood to the feeling itself.',
    'When a mood for or against someone appears, pause before speaking or acting on it.',
    'Set aside the story about that person and locate the feeling within your own experience.',
    'Give the feeling your attention as it changes, without blaming another person or condemning yourself.',
    'Observe the emotion without expressing harm or pretending the situation does not matter.'],
  [25,'Body & stillness','Daily life','Notice awareness in a sudden interruption of movement.',
    'During a simple, safe action, become alert to the impulse moving your body.',
    'Stop the voluntary movement abruptly while you are securely supported. Notice what happens to the impulse and your attention.',
    'Stay aware for a brief moment, then resume comfortably without turning the pause into a struggle.',
    'Never stop essential breathing, suppress a sneeze, or freeze during driving, stairs, or hazardous activity.'],
  [26,'Awareness','Daily life','Withdraw attention from a desire once you see it clearly.',
    'When an ordinary desire arises, first observe it fully: its sensation, image, and pull toward an outcome.',
    'Then abruptly stop feeding its thought or imagined fulfillment. Do not replace it with an opposite desire.',
    'Remain attentive to the space and energy left when the mental pursuit stops.',
    'This concerns a conscious interruption, not punishment, denial of basic needs, or forceful suppression.'],
  [27,'Body & stillness','Movement & rest','Notice the transition from activity into complete rest.',
    'For this gentler adaptation, choose comfortable movement within your normal capacity, in a safe place near a seat or mat.',
    'Stop before strain or exhaustion. Sit or lie down carefully, allowing voluntary effort to end.',
    'Observe the contrast between bodily activity and the awareness that remains as the body rests.',
    'Adaptation: the original uses exhaustion and dropping down. Do not exercise to collapse or imitate a fall.'],
  [28,'Body & stillness','Lying down','Imagine strength draining away while awareness remains.',
    'Lie comfortably with your whole body supported and your breathing unrestricted.',
    'Imagine your strength gradually leaving, as if the body could no longer move. Let muscles release rather than tense.',
    'Stay attentive to the awareness present while movement and effort are absent. End by moving your hands and feet gently.',
    'This is an imagined surrender, never actual deprivation or weakening of the body.'],
  [29,'Love & feeling','Seated','Let devotion absorb the separate sense of self.',
    'Bring to mind a divine presence, teacher, or beloved toward whom devotion comes naturally.',
    'Offer your attention and feeling without bargaining for a result. Let reverence deepen into wholehearted participation.',
    'Allow concern with yourself as a separate observer to soften, remaining with the devotion itself.',
    'A personally meaningful focus matters more than adopting a belief you do not hold.'],
  [30,'Body & stillness','Seated','Let the movements of the closed eyes become quiet.',
    'Sit at ease and close your eyes. Notice whether the eyes still move as thoughts and images pass.',
    'Allow those movements to settle gently, without squeezing the lids or holding the eyes rigidly.',
    'Remain with the inward stillness as mental images quiet. If movement resumes, simply notice and soften again.',
    'Stop if you feel eye strain. The focus is quiet eyes and inward attention, not a body scan.'],
  [31,'Seeing','Seated','See one object as a whole.',
    'Place a simple object, such as a bowl, where you can look at it comfortably.',
    'Take in its whole form at once instead of moving your gaze from one detail to another or describing its material.',
    'Stay with this undivided seeing. When analysis returns, let the entire object meet your gaze again.',
    'Keep the eyes relaxed; blink when needed.'],
  [32,'Seeing','Daily life','Look at the familiar as if seeing it for the first time.',
    'Choose something ordinarily overlooked: a tree, a room, or a familiar face.',
    'Set aside its name and what you already know. Look freshly at the immediate colors, shapes, and presence.',
    'Continue discovering what is actually visible, returning from memory or judgment to direct seeing.',
    'Fresh attention is the practice; you do not need an unusual object.'],
  [33,'Seeing','Outdoors','Let attention open into the clear sky.',
    'Find a comfortable, secure place with a view of blue sky away from the sun.',
    'Let your gaze rest in the open blue rather than following clouds, birds, or imagined shapes.',
    'Allow thought to settle as attention opens into the apparent depth and vastness.',
    'Never look at the sun. Rest your eyes whenever needed.'],
  [34,'Awareness','Teacher-led','Receive a teaching with still, wholehearted attention.',
    'This method belongs to a teacher–student setting; arrange it with a trusted, experienced meditation teacher.',
    'The commentary describes a receptive moment with the senses quiet and the eyes still, listening without inner debate.',
    'Work with the teacher on that quality of listening and readiness, rather than trying to manufacture a dramatic experience alone.',
    'Orientation only. A recording or generic listening exercise is not presented as an equivalent transmission.'],
  [35,'Seeing','Outdoors','Attend to the depth of a well.',
    'Only where there is a secure barrier and safe viewing position, look into a deep well.',
    'Let attention enter the visible depth without tracing the walls or analyzing what is below.',
    'Remain quietly with the sense of depth and spaciousness, then withdraw your gaze gently.',
    'Never lean over an unguarded opening. Skip this method if a safe view is unavailable.'],
  [36,'Seeing','Seated','Withdraw attention from an outer object into inner space.',
    'Look steadily and comfortably at one object, letting attention gather there.',
    'Close your eyes and let the outer gaze turn inward. Notice any remaining image without pursuing its details.',
    'Allow that image to fade and stay with the inward space that is left.',
    'Do not force an afterimage or hold the eyes rigid.'],
  [37,'Sound','Seated','Move from imagined letters through sound and feeling into silence.',
    'Close your eyes and visualize letters inwardly, as though written across awareness. Osho allows any language.',
    'Let their written forms fall away and attend to their imagined sounds; then attend to the feeling beneath those sounds.',
    'When the feeling is clear, release it too and remain quietly without replacing it with another word.',
    'Follow the sequence gently: written form, sound, feeling, then release.'],
  [38,'Sound','Seated','Listen from the center of surrounding sound.',
    'Sit comfortably and close your eyes. Let the sounds around you arrive without selecting a favorite.',
    'Experience the whole field of sound as surrounding you, with yourself at its listening center.',
    'Remain in that center while sounds arise and pass, returning from labels and stories to listening.',
    'Ordinary surroundings are enough; no loud recording or ear closure is needed for this version.'],
  [39,'Sound','Seated','Become absorbed in the vibration of Aum.',
    'Sit comfortably and intone Aum at an easy, unforced volume.',
    'Feel the sound vibrating through the body, allowing the whole body to participate rather than merely hearing a word.',
    'As absorption deepens, let the sound become subtler and inward, staying with its felt resonance.',
    'Keep breathing comfortable. The emphasis is becoming absorbed in sound, not achieving loudness.'],
  [40,'Sound','Seated','Follow a struck sound into silence.',
    'Use a bell or gong at a comfortable volume, or listen to a single clear recorded strike.',
    'Give attention to the entire sound, from its beginning through its gradual fading.',
    'Continue listening after it becomes inaudible, staying with the silence instead of immediately making another sound.',
    'Leave space between repetitions. The optional ending gong can be used for this listening.'],
  [41,'Sound','Seated','Listen for the shared resonance within string music.',
    'Listen to a string instrument or a clear recording at a comfortable volume.',
    'Instead of following separate notes or the tune, attend to the underlying resonance in which the sounds meet.',
    'Let attention become absorbed in that continuous center of sound, returning whenever musical analysis takes over.',
    'This is listening to the whole resonance, not selecting one note.'],
  [42,'Sound','Seated','Let a chosen sound become quieter and more inward.',
    'Choose a sound or word that has a warm, natural resonance for you. Repeat it aloud gently.',
    'As feeling deepens, reduce the volume and let the repetition become inward, without rushing this change.',
    'Eventually let even the inner sound fall away and remain with the feeling it uncovered.',
    'Use a personally meaningful sound; there is no need to force silence.'],
  [43,'Body & stillness','Seated','Rest attention at the center of the tongue.',
    'Relax the jaw and leave your mouth slightly open, without stretching it.',
    'Let attention settle in the middle of the tongue, remaining with the subtle sensation there.',
    'As the tongue becomes quiet, stay attentive to that still center and let breathing remain easy.',
    'The commentary also offers awareness of a natural “hh” breath sound; do not force the exhalation.'],
  [44,'Sound','Seated','Distinguish the middle sound within Aum.',
    'Intone Aum gently and listen closely for its three components: A, U, and M.',
    'As you can distinguish them, leave aside the initial A and final M, attending to the middle U sound.',
    'Remain delicately attentive to that sound, letting the effort to analyze it soften into listening.',
    'This requires sensitivity to sound. If the components are unclear, stay with listening rather than forcing them apart.'],
  [45,'Sound','Seated','Follow the quiet ending of a sound inward.',
    'Choose a word ending in an “ah” sound and repeat it silently.',
    'Attend especially to the final, breath-like “h” as the inner word finishes.',
    'Let attention follow that ending into quiet, resting there before another repetition.',
    'Use the inward-word version here; no forceful emptying or holding of the breath is needed.'],
  [46,'Body & stillness','Teacher-led','Understand the inward-listening method involving a body lock.',
    'Read the commentary: it combines closing the ears with a contraction at the rectal opening.',
    'Its intended focus is the subtle inner sound experienced when attention is gathered inward.',
    'Seek an experienced teacher before attempting the physical lock. Avoid straining, prolonged contraction, or breath restriction.',
    'Orientation only: this app does not teach the physical lock or replace it with an unrelated listening exercise.'],
  [47,'Sound','Seated','Use your own name as a doorway into sound.',
    'Sit quietly and repeat your own name inwardly.',
    'Let its personal associations and meaning recede until it is experienced mainly as sound.',
    'Stay absorbed in that sound, allowing it to open into a wider awareness of sound and silence.',
    'Do not turn the repetition into a story about your identity.'],
  [48,'Love & feeling','With a partner','Remain present with the beginning of intimate union.',
    'With a consenting adult partner, approach intimacy without making a particular outcome the goal.',
    'Attend to the initial warmth and felt connection, allowing the whole experience to unfold slowly.',
    'Remain with that shared presence rather than mentally rushing toward culmination. Keep communicating about comfort.',
    'Do not force prolonged activity or suppress bodily responses. Consent and comfort remain essential.'],
  [49,'Love & feeling','With a partner','Allow spontaneous trembling during intimate union.',
    'During mutually welcome intimacy with an adult partner, remain aware of your whole body.',
    'If natural trembling or shaking arises, allow it without trying to produce a performance or control every movement.',
    'Let awareness include the entire bodily experience instead of concentrating on a single area or desired result.',
    'Do not manufacture shaking or continue through discomfort. Either partner can pause or stop.'],
  [50,'Love & feeling','Seated','Recall the felt experience of intimate union while alone.',
    'Sit alone with your eyes closed and recall a previous, mutually welcome experience of intimate union.',
    'Recover the bodily feeling of connection and absorption rather than replaying a visual story about the partner.',
    'Let that feeling become present in the whole body, with less emphasis on the remembered person or event.',
    'This is the source’s solo recollection method, intended for adults; do not force a memory that feels uncomfortable.'],
  [51,'Love & feeling','Daily life','Turn toward joy as it arises.',
    'When genuine joy appears, such as on meeting a friend after a long separation, become aware of it immediately.',
    'Let attention move from the person or event that triggered it to the feeling of joy itself.',
    'Allow that feeling to spread through your awareness without trying to hold on to its cause.',
    'Use actual joy when it occurs; do not pressure yourself to manufacture happiness.'],
  [52,'Body & stillness','Daily life','Become fully present to taste.',
    'While eating or drinking, pause other activities and take a small, ordinary mouthful.',
    'Attend closely to its taste or coolness as a whole-body experience, rather than immediately naming or evaluating it.',
    'Continue slowly, returning from thought to the direct sensation of each mouthful.',
    'Chew and swallow normally; never prolong holding food or liquid in a way that feels unsafe.'],
  [53,'Awareness','Daily life','Remember your own presence while sensing and acting.',
    'During a simple activity, notice what you are seeing, hearing, or doing.',
    'At the same time, feel that you are here, aware of the activity. Let this be a felt presence, not a repeated slogan.',
    'Keep both the experience and your own presence in awareness, returning gently whenever you become lost in the activity.',
    'Begin with safe, undemanding situations.'],
  [54,'Love & feeling','Daily life','Stay with a moment of contentment.',
    'Notice a real moment of satisfaction, however small, when nothing else seems necessary.',
    'Turn attention to that contentment instead of immediately seeking the next pleasure or improvement.',
    'Remain with the feeling as long as it naturally lasts, without clinging when it changes.',
    'The starting point is contentment already present, not an instruction to deny dissatisfaction.'],
  [55,'Rest & sleep','Lying down','Observe the transition from waking into sleep.',
    'Lie comfortably at your usual bedtime, close your eyes, and let the body relax.',
    'Watch the changing boundary between ordinary wakefulness and the first signs of sleep.',
    'Remain gently aware as thoughts become dreamlike, allowing sleep to take over without struggling to retain control.',
    'Do not sacrifice sleep or treat staying awake as success.'],
  [56,'Awareness','Daily life','Contemplate experience as dreamlike appearance.',
    'During an ordinary moment, regard what you see and think as passing appearances, like scenes in a dream.',
    'Notice how readily you become caught by these scenes, and return to observing their changing quality.',
    'Carry this lightness into the next activity while remaining present and responsive.',
    'This is a contemplative perspective, not a claim that people, consequences, or responsibilities are unreal.'],
  [57,'Awareness','Daily life','Find the witnessing center within a strong feeling.',
    'When a strong desire or emotion arises naturally, pause somewhere safe.',
    'Feel its movement while also noticing the awareness that can observe it.',
    'Rest attention in that observing center without expressing harm, suppressing the feeling, or feeding its story.',
    'Do not deliberately provoke anger or distress to create an opportunity.'],
  [58,'Awareness','Daily life','See changing events as scenes in a play.',
    'Observe an ordinary situation as though watching a scene unfold on a stage.',
    'Notice your role, the other roles, and the changing circumstances without becoming entirely identified with them.',
    'Continue participating with care, carrying a lighter sense of play into what you do.',
    'Playfulness can coexist with responsibility and concern for others.'],
  [59,'Awareness','Daily life','Remain a witness between pleasure and pain.',
    'When a pleasant or unpleasant feeling appears, notice its actual qualities before reacting.',
    'Observe the impulse to cling to pleasure or reject discomfort, without immediately following either impulse.',
    'Rest in the awareness that notices both as changing experiences.',
    'This concerns your relationship to sensation; do not ignore pain that calls for practical care.'],
  [60,'Love & feeling','Daily life','Understand impulses without condemnation.',
    'Notice an impulse in yourself that you would usually judge harshly.',
    'Recognize it as part of shared human experience, allowing it to be seen without self-condemnation.',
    'Extend that understanding toward others while choosing your actions consciously.',
    'Understanding an impulse does not require acting on it or accepting harmful behavior.'],
  [61,'Awareness','Seated','Contemplate yourself as a wave of the whole.',
    'Sit quietly and bring to mind waves arising from water and returning to it.',
    'Feel your own changing body, thoughts, and life as expressions of a larger existence, like a wave within the sea.',
    'Let attention rest in this sense of continuity rather than defending a sharply separate identity.',
    'Use the wave as a contemplative image, without needing to prove a theory.'],
  [62,'Awareness','Seated','Let the mind wander within a wider awareness.',
    'Sit comfortably and stop trying to force attention onto a single object.',
    'Let the mind move where it naturally moves, while remaining aware of the spacious background in which thoughts appear.',
    'When you become absorbed in a thought, notice that too and reopen awareness without fighting the mind.',
    'The emphasis is an open background, not following every thought into a story.'],
  [63,'Awareness','Seated','Attend to the experiencer behind a sense impression.',
    'Choose a clear, ordinary sight or sound and give it your full attention.',
    'While it is vivid, turn attention toward the awareness that is seeing or hearing it.',
    'Stay with that felt knowing rather than searching for a verbal answer about who you are.',
    'Both the sense impression and the awareness of it can remain present.'],
  [64,'Awareness','Daily life','Be alert at the onset of a sudden sensation.',
    'Notice an ordinary, naturally occurring moment such as the first feeling of hunger or a harmless surprise.',
    'At its onset, turn toward the brief interruption of habitual thought and the immediacy of the experience.',
    'Remain aware as the moment passes, then respond normally to what the body or situation needs.',
    'Do not create fear, danger, deprivation, or a suppressed sneeze for this exercise.'],
  [65,'Awareness','Daily life','Notice experience before dividing it into pure and impure.',
    'Watch a moment when your mind labels something as spiritually pure, impure, superior, or inferior.',
    'Set the label aside briefly and attend to what is actually being experienced.',
    'Remain with this less divided awareness before choosing a thoughtful response.',
    'Dropping inner condemnation does not remove ethical boundaries or practical discernment.'],
  [66,'Awareness','Daily life','Notice the steady witness through changing circumstances.',
    'Observe how your feelings change with praise or criticism, familiarity or strangeness.',
    'Turn attention from those changing reactions toward the awareness that notices each one.',
    'Return to that witnessing presence through different situations, without insisting that feelings stay the same.',
    'The continuity is in witnessing; it is not forced indifference toward people.'],
  [67,'Awareness','Daily life','Allow change without trying to freeze it.',
    'Notice a changing experience, such as a sound, a mood, or the movement of daily life.',
    'Let it unfold without trying to hold one phase permanently or resist the next.',
    'Remain aware of the whole flow and of the witnessing presence in which change is noticed.',
    'Use ordinary experience; the image of a river does not require entering water.'],
  [68,'Awareness','Daily life','Return from imagined futures to what is real now.',
    'Notice when you postpone living until a hoped-for future. Bring attention back to the situation actually present.',
    'Distinguish what you know through direct experience from beliefs you have merely borrowed or repeated.',
    'Give yourself to a real action now, acting from your own understanding rather than imitating a role or rehearsing a future.',
    '“Hope-less” here concerns releasing postponement and fantasy, not cultivating despair or abandoning practical plans.'],
  [69,'Awareness','Seated','Look beyond the mental pair of bondage and freedom.',
    'Notice a thought that describes you as bound, limited, or in need of a future state called freedom.',
    'See how the opposing ideas depend on each other. For a moment, stop choosing either description.',
    'Rest in present awareness without making liberation another imagined possession to acquire.',
    'This explores mental identification; it does not deny real restrictions or the need to change them.'],
  [70,'Light & space','Seated','Imagine light rising through the inner centers.',
    'Sit comfortably with eyes closed and imagine your inner substance as light.',
    'Begin at the base or sexual center. Imagine a stream of light rising to the navel, then to the heart.',
    'Let the imagined light continue upward toward the crown, allowing each center to become luminous before moving on.',
    'This is visualization. Do not force breath, muscular locks, heat, or other physical effects.'],
  [71,'Light & space','Seated','Imagine light flashing from center to center.',
    'Sit at ease with your eyes closed and bring attention to the base of the spine.',
    'Imagine a bright flash passing upward from one inner center to the next, rather than a continuous stream.',
    'Let the flashes reach the crown and remain quietly with the sense of light and spaciousness.',
    'Keep the imagery comfortable; do not intensify it through strain or rapid breathing.'],
  [72,'Love & feeling','Daily life','Meet your surroundings as living presence.',
    'Choose a simple encounter with nature, such as resting a hand gently on a tree.',
    'Feel the contact directly and approach what you meet as a living presence rather than an object for use.',
    'Remain receptive to the sense of relationship and aliveness, without demanding an unusual response.',
    'This is an attitude of felt connection, not a test for supernatural communication.'],
  [73,'Light & space','Outdoors or seated','Let outer clarity open into inner clarity.',
    'Look comfortably into a clear, open sky away from the sun, allowing the view to feel undivided.',
    'Close your eyes and carry the quality of openness inward, as though awareness itself were a clear sky.',
    'Let thoughts pass like clouds without disturbing the background spaciousness.',
    'The commentary also allows an inward sky contemplation when an outdoor view is unavailable.'],
  [74,'Light & space','Seated','Imagine your awareness expanding to include the whole world.',
    'Close your eyes and feel the outline of your body.',
    'Imagine that outline expanding gradually: beyond the body, through the room, and outward into the world.',
    'Continue until the whole expanse seems included within you, rather than yourself being a small object inside it.',
    'Work as imagery, at a comfortable pace; do not force a physical sensation of expansion.'],
  [75,'Light & space','Daily life & sleep','Carry the image of yourself as light into rest.',
    'During quiet moments of the day, imagine your own presence as light rather than a solid outline.',
    'Return to this luminous feeling gently in different situations, without needing to see a visible glow.',
    'At bedtime, let the same feeling accompany you into sleep as the body relaxes.',
    'Do not stay awake to maintain the image or expect a particular dream or visible aura.'],
  [76,'Light & space','Seated','Let the darkness of night surround you.',
    'Sit in a familiar, safe place at night where it is naturally dark and you will not need to move around.',
    'Keep your eyes comfortably open and receive the darkness, rather than searching for shapes or resisting it.',
    'Allow the feeling of darkness to surround and include your whole body, remaining quietly aware.',
    'Keep a light available. Stop if darkness brings fear or distress.'],
  [77,'Light & space','Seated','Carry inner darkness into open-eyed awareness.',
    'Close your eyes in a comfortable place and notice the darkness within.',
    'Let attention become familiar with that quiet inner darkness without inventing a scene.',
    'Open your eyes gently and try to retain its inward quality while seeing the room normally.',
    'This is continuity of attention, not an attempt to make your vision physically dark.'],
  [78,'Awareness','Seated','Stay fully where attention has already landed.',
    'Notice the object or experience on which your attention naturally rests at this moment.',
    'Remain there completely instead of immediately searching for something else or judging whether it is suitable.',
    'Let the mind settle through wholehearted attention, returning when you begin moving away in thought.',
    'Unlike open wandering, this method gives full attention to the present focus.'],
  [79,'Light & space','Lying down','Imagine the body dissolving in fire while you witness.',
    'Lie supported with eyes closed. Only if this imagery feels comfortable, imagine fire beginning at your toes.',
    'Let the imagined fire move gradually upward through the body, leaving ashes behind.',
    'When the image of the body has dissolved, remain with the awareness witnessing the whole process.',
    'Visualization only: never use actual fire. Choose another method if death imagery is distressing.'],
  [80,'Light & space','Seated','Imagine the world dissolving while awareness remains.',
    'Sit with eyes closed and bring the surrounding world to mind.',
    'Imagine that entire scene consumed by fire and disappearing, rather than following the fate of individual objects.',
    'When nothing remains in the imagined scene, rest in the awareness that witnessed its disappearance.',
    'Use no actual fire. Skip this visualization if destruction imagery is upsetting.'],
  [81,'Body & stillness','Seated','Feel separate impressions meeting in one whole experience.',
    'Sit quietly and notice the impressions arriving through your senses, such as sound and the touch of air.',
    'Let them be felt throughout your being rather than assigning each to an isolated body part.',
    'Remain with the unified experience in which these different impressions converge.',
    'The emphasis is felt wholeness, rather than intellectually assembling a list of sensations.'],
  [82,'Love & feeling','Seated','Move from thinking about yourself to directly feeling within.',
    'Begin with an immediate sensation, such as the warmth of contact or the texture beneath your hand. Feel before naming.',
    'Turn that direct attention inward to thoughts and the sense of “I,” observing them without defining yourself by them.',
    'Let attention deepen toward the inner capacity for knowing itself, remaining with felt presence rather than borrowed self-descriptions.',
    'In this commentary, “internal organs” refers to inner knowing and awareness, not an anatomical body scan.'],
  [83,'Awareness','Seated','Notice the intervals before and after a thought or desire.',
    'Sit quietly and observe a thought or desire as it begins to appear.',
    'Notice the interval before it forms, then watch it pass and notice the interval after it ends.',
    'Rest in those intervals without supplying a new thought about who you are or what should happen.',
    'Let thoughts come naturally; do not try to force an empty mind.'],
  [84,'Light & space','Seated','Explore awareness beyond the boundary of the body.',
    'Sit quietly and notice the habit of locating your whole identity inside the body.',
    'Let attention open outward to the surrounding space, as though awareness were not confined by the skin.',
    'Remain with this wider field, allowing the body to be included without being its only reference point.',
    'Treat this as contemplation. Stop if you feel disoriented and return to ordinary sensory contact.'],
  [85,'Awareness','Seated','Rest without choosing an object for thought.',
    'Sit comfortably and allow attention to become open, without selecting a word, image, or problem to work on.',
    'When a particular thing becomes the focus, let it pass rather than replacing it with another object.',
    'Remain in the openness between objects of thought, without making “nothing” into an image to hold.',
    'This is not a contest to suppress thought; release objects gently.'],
  [86,'Awareness','Seated','Explore the point where imagining reaches its limit.',
    'Quietly consider something that cannot be perceived, pictured, or grasped by the mind.',
    'Notice that each image or definition you produce is still something graspable, and let that attempt go.',
    'As the effort to form an answer falls away, remain with the open awareness left at that limit.',
    'The exercise is not to find a clever answer or become frustrated with an impossible task.'],
  [87,'Love & feeling','Seated or lying','Feel the simple fact of existing.',
    'Sit or lie quietly and turn from descriptions of yourself to the immediate feeling that you exist.',
    'Let this be sensed through your whole being, especially the heart, rather than repeated as a sentence.',
    'Rest in the felt reality of this existence as already present, without adding a role, achievement, or comparison.',
    'Stay with the feeling, not a verbal argument about “I am.”'],
  [88,'Awareness','Seated','Include both what is known and the one knowing it.',
    'Give one object, such as a flower, your undivided attention until other concerns recede.',
    'Without losing the object, become aware of yourself as its experiencer.',
    'Hold both in awareness together, allowing a witnessing position that is not identified exclusively with either.',
    'The sequence moves from object, to subject, to awareness of both.'],
  [89,'Light & space','Seated','Let the outside world be included within your being.',
    'Look at a nearby tree or the open sky, avoiding direct sunlight.',
    'Close your eyes and feel that what you saw is included within you, rather than standing apart from you.',
    'Gradually include body, breath, thought, and the surrounding world in this one field of experience.',
    'Explore inclusion through feeling; there is no need to imagine physical possession or enlargement.'],
  [90,'Body & stillness','Seated','Touch the closed eyes with almost no weight.',
    'Sit relaxed, close your eyes, and use clean hands. Rest your palms very lightly over the closed eyes.',
    'Keep the touch feather-light, with no pressure on the eyes. Remain aware of that delicacy throughout.',
    'Notice any sense of lightness between the eyes and allow it to spread toward the heart and through your awareness.',
    'Never press or rub the eyeballs. If contact is uncomfortable, stop; do not prolong it to match the timer.'],
  [91,'Light & space','Seated','Contemplate a subtle presence surrounding the body.',
    'Sit with eyes closed and become aware of the body’s outline, from the feet through the whole form.',
    'Imagine a soft, bluish presence within and around that outline, extending above and below it.',
    'Remain quietly with this subtle form, allowing it to feel spacious without manipulating it.',
    '“Etheric body” is the source’s spiritual model; a visible aura is not a required result.'],
  [92,'Love & feeling','Seated','Let attention become subtle and centered in the heart.',
    'Sit quietly and turn from analyzing experience toward directly feeling it, as when appreciating a flower without describing it.',
    'Let attention settle in the heart area and become gentle and fine, including the space above and below it.',
    'Remain with the whole feeling as thoughts quiet, without trying to define or capture the experience.',
    'The commentary emphasizes a shift from intellectual division to wholehearted feeling.'],
  [93,'Light & space','Seated or lying','Imagine one region of the body as limitless space.',
    'Relax with eyes closed and choose one region, such as the inside of the head.',
    'Imagine its boundaries gradually moving outward, making the interior increasingly spacious.',
    'Allow the imagined limits to disappear and rest in the resulting expanse.',
    'Use imagery without physical effort. Return to feeling the seat or floor if you become disoriented.'],
  [94,'Love & feeling','Daily life','Feel the whole body permeated by a larger life.',
    'In a quiet moment, imagine every part of the body, including flesh, blood, and bones, filled with a sacred or cosmic presence.',
    'Let the feeling permeate the whole form rather than remaining an idea in the head.',
    'Carry it into simple acts of eating, resting, and waking, experiencing them as movements of that larger life.',
    'This summarizes the central saturation practice; the commentary also discusses contrasting moods as preparation.'],
  [95,'Body & stillness','Seated','Attend gently to the bodily center specified in the method.',
    'Read the source’s two alternatives: attention to both breasts together, or attention to the root of the penis.',
    'Seated privately and relaxed, rest attention at the relevant area without touch, muscular effort, or trying to create arousal.',
    'Allow any felt softness or creativity to spread through awareness, observing without clinging to a particular sensation.',
    'For adults. The source’s gender and energy explanations are traditional claims, not established anatomy or predictions.'],
  [96,'Light & space','Outdoors','Rest your gaze in an unobstructed expanse.',
    'Choose a safe, open place with a broad view and few nearby visual obstructions.',
    'Sit comfortably and allow your gaze to open into the distance without searching for a particular object.',
    'Remain receptive to the spaciousness, letting the usual pressure to focus or think settle.',
    'Avoid looking at the sun and keep away from exposed edges or unsafe terrain.'],
  [97,'Light & space','Seated or outdoors','Let spacious silence become a felt body of ease.',
    'Become aware of the space around you, preferably in a quiet natural setting.',
    'First feel that expanse as filled with silence. Let even gentle sounds belong within it.',
    'If ease or joy emerges, let it fill the same expanse, as though the whole space were your body of well-being.',
    'Begin with silence as the commentary suggests; do not manufacture bliss.'],
  [98,'Love & feeling','Seated or lying','Let peace spread through the chest.',
    'Choose an easy, supported position and let unnecessary bodily tension release.',
    'Close your eyes and attend to the chest between the armpits, feeling that whole area together.',
    'Imagine and feel peace gradually pervading this area, allowing attention to rest there.',
    'Let the feeling develop gently; no breath manipulation or muscular tightening is required for this central step.'],
  [99,'Light & space','Seated','Expand from the heart without drawing a boundary.',
    'Sit quietly and notice the tendency to contract or protect a narrow sense of self.',
    'From the heart area, feel your presence extending in every direction, both near and far.',
    'Let that expansion continue without deciding where you end, resting in the sense of a center without an edge.',
    'Explore openness inwardly while keeping ordinary practical boundaries and bodily comfort.'],
  [100,'Awareness','Daily life','Recover the witness when something captures you.',
    'Notice when an attractive object or event begins pulling you into desire and away from self-awareness.',
    'Take one comfortable, fuller breath and let it out. As you exhale, look at the same thing again.',
    'See it as a witness, aware of yourself as well as the object, then choose your response rather than being carried away.',
    'No forceful breathing is needed. Detachment here does not require withdrawing from life.'],
  [101,'Light & space','Seated','Contemplate awareness without the usual bodily limits.',
    'Close your eyes and imagine the body’s boundaries melting, while awareness remains present.',
    'Let that awareness feel unrestricted by one location, opening into the surrounding space.',
    'Within this contemplation, explore the source’s image of an all-pervading consciousness without returning to personal comparisons.',
    'A spiritual contemplation, not evidence of literal omniscience, invulnerability, or control over events.'],
  [102,'Light & space','Seated','Imagine one spiritual presence within and around you.',
    'Sit quietly, preferably in nature or an undisturbed room, and close your eyes.',
    'Imagine consciousness flowing within the body and throughout the surrounding space at the same time.',
    'Allow the distinction between inner and outer to soften until the entire scene feels permeated by one presence.',
    'This is an imaginative meditation; let it remain gentle and unforced.'],
  [103,'Awareness','Daily life','Meet a desire at its first appearance without fighting it.',
    'Notice a desire as early as possible, before it develops into a chain of thought or action.',
    'Give that first movement your full attention, without condemning, indulging, or trying to destroy it.',
    'Observe what happens to the desire under this undivided awareness, remaining present if it changes or fades.',
    'Unlike a forceful interruption, this method emphasizes a complete, non-hostile look.'],
  [104,'Awareness','Seated','Look beyond the limits of a particular perception.',
    'Attend to something you can perceive, such as a section of sky or one sound.',
    'Notice that your perception shows only a limited part. Let attention open toward what lies beyond its apparent boundary.',
    'Whenever another limit appears, release that limit too and remain with the widening sense of the unknown.',
    'You need not picture infinity successfully; explore the limits of perception without strain.'],
  [105,'Love & feeling','Daily life','Contemplate the same consciousness in every form.',
    'Look at yourself and the beings or things around you as expressions of one underlying existence.',
    'Extend the same regard to what you would usually consider separate, lesser, or unimportant.',
    'Let the contemplation soften your sense of superiority or isolation, remaining attentive to each particular form.',
    'The method’s emphasis is shared being and humility, not claiming a special status for yourself.'],
  [106,'Love & feeling','Daily life','Enter another being’s experience with less self-concern.',
    'Begin with a tree, river, or person you can approach with ease and respect.',
    'Set your self-preoccupation aside and imaginatively feel their presence from within, rather than merely describing it from outside.',
    'Allow a sense of shared life to develop while remaining sensitive to the other’s actual boundaries and needs.',
    'This explores empathy and union; do not assume you literally know another person’s private thoughts.'],
  [107,'Love & feeling','Daily life','Meet all existence as an expression of consciousness.',
    'During an ordinary activity, approach what you encounter as a manifestation of consciousness rather than dead material.',
    'Bring care and awareness to the way you touch, handle, and relate to it.',
    'Let this attitude extend beyond one object to the whole situation, including yourself.',
    'Use this as the source’s contemplative perspective, not a scientific claim about objects.'],
  [108,'Awareness','Seated','Listen inwardly after habitual thinking settles.',
    'Choose a small, non-urgent question. Sit quietly and allow repetitive analysis to settle without forcing an answer.',
    'Attend to what emerges inwardly, noticing the difference between a quiet felt response and continued mental argument.',
    'Consider that response after the meditation and check it against the practical situation before acting.',
    'Everyday adaptation: do not use intuition in place of navigation, evidence, or help in an emergency.'],
  [109,'Light & space','Seated','Imagine the body as an empty room.',
    'Sit comfortably upright, letting the body relax around its support.',
    'Imagine the skin as the walls of a room and the interior as completely empty.',
    'Stay with this inward emptiness, letting sensations and thoughts pass without mentally furnishing the room again.',
    'This is imagery, not a denial of the body or its needs.'],
  [110,'Awareness','Daily life','Bring a spirit of play into activity and thought.',
    'Choose an ordinary activity and approach it as play, with less pressure to prove yourself or secure a result.',
    'Watch the mind’s changing scenes and thoughts as a game unfolding in an open space.',
    'Participate fully while holding those scenes lightly, returning to playfulness when you become rigidly identified with them.',
    'Keep care for people and consequences while relaxing unnecessary seriousness.'],
  [111,'Awareness','Seated','Contemplate opposites, then release both.',
    'Choose a pair such as knowing and not knowing, or existence and non-existence.',
    'Bring each side into awareness and notice how the mind moves between them.',
    'Set both descriptions aside together, remaining present without choosing a third explanation.',
    'The aim is release from the pair, not winning an argument about which side is true.'],
  [112,'Awareness','Seated','Rest inwardly without a chosen support.',
    'Sit quietly, close your eyes, and let the body settle comfortably.',
    'For this method, leave aside deliberate mantras, images, and objects of concentration.',
    'Remain in inward stillness without searching for another support. When grasping returns, notice it and let go again.',
    'If unsupported sitting feels too difficult, choose a more structured technique for now.']
];

const adapted = new Set([11,27,108]);
const teacherLed = new Set([15,34,46]);
// The catalogue pages for these entries contain another technique's commentary.
const correctedSources = {
  3:'https://oshoworld.com/vigyan-bhairav-tantra-vol-1-03',
  4:'https://oshoworld.com/vigyan-bhairav-tantra-vol-1-03',
  5:'https://oshoworld.com/vigyan-bhairav-tantra-vol-1-05',
  100:'https://oshoworld.com/vigyan-bhairav-tantra-vol-2-33'
};
export const practiceGuides = Object.fromEntries(rows.map(([number,theme,format,intro,...text]) => {
  const steps=text.slice(0,3),tip=text[3];
  const mode=teacherLed.has(number)?'Teacher-led method':adapted.has(number)?'Adapted practice':'Practical summary';
  return [number,{number,theme,format,intro,steps,tip,mode,source:correctedSources[number] || null}];
}));
