// Static instructional diagrams: no breath pacing, flashing, or anatomical claims.
const text=(x,y,value,extra='')=>`<text x="${x}" y="${y}" text-anchor="middle" ${extra}>${value}</text>`;
const circle=(x,y,r,extra='')=>`<circle cx="${x}" cy="${y}" r="${r}" ${extra}/>`;
const diagrams={
  breath:{title:'The natural breath cycle',description:'Inhale and exhale form a continuous loop. Two small markers identify the natural changes of direction, without prescribing a pause length.',body:'<path d="M110 88 C110 16 250 16 250 88 M250 92 C250 164 110 164 110 92"/><path d="m243 79 7 12 7-12 M103 101l7-12 7 12"/>'+circle(110,90,5,'class="diagram-accent"')+circle(250,90,5,'class="diagram-accent"')+text(180,22,'Inhale')+text(180,176,'Exhale')+text(52,88,'Turn')+text(308,88,'Turn'),caption:'Follow your own breath. The dots mark transitions, not timed holds. Read the steps to see which transition this practice attends to.'},
  colors:{title:'Five colors, then openness',description:'Five colored circles sit in a spacious field. An arrow leads toward an open circle, representing release of the mental image.',body:['#dec19b','#9bd1c2','#aabcec','#d6a2ba','#d8d39d'].map((c,i)=>circle(72+Math.cos(i*1.257)*27,82+Math.sin(i*1.257)*27,10,`style="fill:${c};stroke:${c}"`)).join('')+'<path d="M140 85h60m-8-6 8 6-8 6"/>'+circle(275,85,43,'stroke-dasharray="4 7"')+text(74,151,'Imagine')+text(274,151,'Release'),caption:'Imagine the colors with eyes resting closed. Let the mental picture soften; this screen is a reference, not something to stare at.'},
  axis:{title:'An imagined central line',description:'A fine vertical line rises from a base point through several illustrative points into open space. These points are not a specified chakra map.',body:'<path d="M180 142V40m-6 9 6-9 6 9" stroke-dasharray="3 5"/>'+[65,92,119,142].map(y=>circle(180,y,4,'class="diagram-accent"')).join('')+text(78,146,'Base')+text(273,40,'Open space'),caption:'An attention map only. Use the written direction for this technique; the points do not locate nerves or prescribe a chakra system.'},
  heart:{title:'A broad, gentle center',description:'An open oval represents the chest region, with a softly marked center as an attentional area. No physical pressure or breathing pattern is prescribed.',body:'<ellipse cx="180" cy="83" rx="77" ry="46" stroke-dasharray="4 6"/>'+circle(180,83,23,'class="diagram-accent diagram-soft"')+text(180,158,'Attention, without pressure'),caption:'Let attention rest broadly in the chest area described in the steps. This is a focus of awareness, not a physical point to press.'},
  gaze:{title:'One object, gentle attention',description:'A small central circle represents a single chosen object. The surrounding space remains quiet and uncluttered.',body:circle(180,78,23,'class="diagram-accent"')+text(180,145,'One object · soft eyes'),caption:'Choose a real, ordinary object in a comfortable position. Blink freely; there is no need to fix your eyes on this diagram.'},
  bowl:{title:'Attend to the space inside',description:'A bowl outline surrounds an open area. A label points into the opening rather than at the sides of the bowl.',body:'<path d="M89 58Q98 140 180 140Q262 140 271 58"/><ellipse cx="180" cy="58" rx="91" ry="17"/>'+text(180,94,'Space')+'<path d="M180 79V63"/>',caption:'Use an empty cup or bowl. Let the interior space be the focus, with the material and rim in the background.'},
  listening:{title:'Sound and the knowing of sound',description:'Several concentric arcs surround a small listening center. They represent a field of sound rather than different objects to track.',body:[30,57,83].map(r=>circle(180,88,r,'stroke-dasharray="3 6"')).join('')+circle(180,88,7,'class="diagram-accent"')+text(48,92,'Sound')+text(311,92,'Sound'),caption:'Receive the sound as a whole, then notice the listening of it. The center is experiential; you do not need to locate a point in your head.'},
  fade:{title:'From sound toward quiet',description:'A row of decreasing vertical marks gives way to open space, showing sound becoming subtler and ending.',body:[58,52,47,41,34,28,21,15,9,4].map((h,i)=>`<path d="M${45+i*21} ${85-h/2}v${h}"/>`).join('')+'<path d="M275 85h42" stroke-dasharray="2 8"/>'+text(78,146,'Sound')+text(280,146,'Quiet'),caption:'Follow the actual or imagined sound described in the steps. The drawing has no time scale; do not lengthen breath to match it.'},
  vowel:{title:'The middle vowel of A-U-M',description:'A and M are muted. U is emphasized as the selected component of the Reps/Osho formulation.',body:text(82,102,'A','class="diagram-muted diagram-letter"')+text(180,102,'U','class="diagram-letter diagram-highlight"')+text(278,102,'M','class="diagram-muted diagram-letter"')+text(180,153,'A gentle “oo” quality'),caption:'Attend to U without adding the initial A or closing M. This is the Reps/Osho formulation; the source note explains the Sanskrit difference.'},
  middle:{title:'Release both positions',description:'Two separate circles stand for two mental positions. A small open space between them represents attention no longer committed to either side.',body:circle(80,83,29)+circle(280,83,29)+'<path d="M120 83h26m94 0h-26" stroke-dasharray="3 5"/>'+text(180,90,'Rest')+text(80,148,'One side')+text(280,148,'Other side'),caption:'Notice the two positions in the written practice, then release following either one. The middle is not a physical location.'},
  abovebelow:{title:'Above and below, together',description:'Two open circles represent space above and below a central reference point. The practice includes both directions simultaneously.',body:circle(180,31,24,'stroke-dasharray="3 5"')+circle(180,145,24,'stroke-dasharray="3 5"')+circle(180,88,5,'class="diagram-accent"')+text(274,37,'Above')+text(274,151,'Below')+'<path d="M180 60v12m0 32v12"/>',caption:'Hold both directions lightly at once. Keep the body supported and remain oriented to the room.'},
  three:{title:'Three areas held together',description:'Three open circles represent above, heart, and below. None is a point to physically manipulate.',body:[32,89,146].map(y=>circle(142,y,23,'stroke-dasharray="3 5"')).join('')+text(245,38,'Above')+text(245,95,'Heart')+text(245,152,'Below'),caption:'Imagine all three regions as open at the same time. Do not strain to hold a precise picture.'},
  space:{title:'An open field of attention',description:'A dashed inner boundary sits within a wider open field, suggesting spacious awareness that can include body and surroundings.',body:circle(180,84,29,'stroke-dasharray="3 5"')+'<ellipse cx="180" cy="84" rx="127" ry="66" stroke-dasharray="3 8"/>'+text(180,174,'Include · soften · rest'),caption:'The boundary is a visual metaphor. Follow the particular region or direction in the steps and keep a sense of actual bodily support.'},
  wave:{title:'A wave remains water',description:'One wave rises and settles along a continuous waterline, illustrating a temporary form belonging to a larger whole.',body:'<path d="M28 103C57 103 75 103 94 78S124 29 150 55S172 120 200 103S237 77 258 94S304 103 332 103"/>'+text(128,30,'Wave')+text(180,157,'The same water'),caption:'Use this as an image of continuity: the changing shape never becomes separate from the water. Then let the image go.'}
};
const groups={breath:[1,2,3,4,6,8],colors:[13],axis:[14,70,71],heart:[16,98],gaze:[18,32],bowl:[31],listening:[38,41],fade:[39,40,42,45,47],vowel:[44],middle:[17,59,111],abovebelow:[91],three:[92],space:[84,93,94,96,99,102,109,112],wave:[61]};
export const visualMap=Object.fromEntries(Object.entries(groups).flatMap(([key,numbers])=>numbers.map(n=>[n,key])));
export const visualFor=number=>diagrams[visualMap[number]] || null;
export function renderVisual(number){
  const v=visualFor(number);if(!v)return '';
  return `<figure><svg viewBox="0 0 360 185" role="img" aria-labelledby="visual-title visual-description"><title id="visual-title">${v.title}</title><desc id="visual-description">${v.description}</desc><g>${v.body}</g></svg><figcaption>${v.caption}</figcaption></figure>`;
}
